// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA69iRhadZxTLAW_z7nm-dS7WYOsfE8lRo',
    appId: '1:674222803730:web:a7aa043631f70f4c37c1cb',
    messagingSenderId: '674222803730',
    projectId: 'sy-nav',
    authDomain: 'sy-nav.firebaseapp.com',
    storageBucket: 'sy-nav.appspot.com',
    measurementId: 'G-TS8YQ2MBL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADpi23LeN-8pI4uCHHHuYbvKEEKAr_Oek',
    appId: '1:674222803730:android:b7f77279333bd22b37c1cb',
    messagingSenderId: '674222803730',
    projectId: 'sy-nav',
    storageBucket: 'sy-nav.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKlMskqFJmaAZGQpIsCKkY6v0TknXiS7I',
    appId: '1:674222803730:ios:a7f6a4b15a71e2eb37c1cb',
    messagingSenderId: '674222803730',
    projectId: 'sy-nav',
    storageBucket: 'sy-nav.appspot.com',
    iosBundleId: 'com.example.syNav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKlMskqFJmaAZGQpIsCKkY6v0TknXiS7I',
    appId: '1:674222803730:ios:092442247b5206a737c1cb',
    messagingSenderId: '674222803730',
    projectId: 'sy-nav',
    storageBucket: 'sy-nav.appspot.com',
    iosBundleId: 'com.example.syNav.RunnerTests',
  );
}
